name: Clone and Show Repo Files

on:
  push:
    branches:
      - main

jobs:
  show-code:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Clone this repo
        uses: actions/checkout@v3

      - name: 📂 List project files
        run: ls -la

      - name: 📄 Show contents of index.php
        run: cat index.php
